### ISSUE TITLE
How do I use it with parcel?

### ISSUE THREAD

**Issue by lkaratun** [HarryStevens/d3-moveto#1]
Hi, thanks for the package, it's pretty handy!
I was just wondering if you could help me with using it with parcel bundler? 
Initially I used it with a simple http server by including it in a script tag in my index.html and it worked fine. However, when I try to do `import "d3-moveto";` and later try to use the `moveToFront` function, I get an error: `selection.moveToFront is not a function`

What am I doing wrong? 
Thanks in advance!

**Comment by HarryStevens** [comment]
Just use d3.raise() and d3.lower() from d3-selection.

**Comment by lkaratun** [comment]
Thanks!
